### ISSUE TITLE
Wrong Success Message

### ISSUE THREAD

**Issue by toddca** [mrgrt/woocommerce-coupon-codes-renamed#2]
I rename my codes as "promo code" and everything works great (thanks a ton for this!), but I do have one small issue. When a valid promo code is added WooCommerce displays a success message and it reads: "promo code code applied successfully." - Notice the two "code" words. I am not sure how to fix this as I do not see a success message in the code however if you could point out or provide a tip around where I should be focusing my efforts I will fix and submit a pull request. I am on the latest version of WooCommerce which may actually be the issue here.

**Comment by mrgrt** [comment]
Hi @toddca . Were you able to resolve this issue?

**Comment by toddca** [comment]
@mrgrt I don't believe I ever found a solution. It is not a site I work on all that often so I have not checked back with the team to understand if this is still an issue but I for one never did find a fix otherwise I would have sent a pull.

**Comment by mrgrt** [comment]
@toddca I think this should be fixed now. Please see https://github.com/mrgrt/woocommerce-coupon-codes-renamed/commit/0531e88c4a539d3dcb4fa3fab0dfee4a61daccd1
